version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./model:/app/model
    environment:
      - CUDA_VISIBLE_DEVICES=
      - TORCH_DEVICE=cpu

# docker compose down
# docker compose up --build